/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetTemplates200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplates200Response{}

// GetTemplates200Response struct for GetTemplates200Response
type GetTemplates200Response struct {
	Data []Template `json:"data,omitempty"`
}

// NewGetTemplates200Response instantiates a new GetTemplates200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplates200Response() *GetTemplates200Response {
	this := GetTemplates200Response{}
	return &this
}

// NewGetTemplates200ResponseWithDefaults instantiates a new GetTemplates200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplates200ResponseWithDefaults() *GetTemplates200Response {
	this := GetTemplates200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTemplates200Response) GetData() []Template {
	if o == nil || IsNil(o.Data) {
		var ret []Template
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplates200Response) GetDataOk() ([]Template, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTemplates200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Template and assigns it to the Data field.
func (o *GetTemplates200Response) SetData(v []Template) {
	o.Data = v
}

func (o GetTemplates200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplates200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetTemplates200Response struct {
	value *GetTemplates200Response
	isSet bool
}

func (v NullableGetTemplates200Response) Get() *GetTemplates200Response {
	return v.value
}

func (v *NullableGetTemplates200Response) Set(val *GetTemplates200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplates200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplates200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplates200Response(val *GetTemplates200Response) *NullableGetTemplates200Response {
	return &NullableGetTemplates200Response{value: val, isSet: true}
}

func (v NullableGetTemplates200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplates200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


