/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetLists200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetLists200Response{}

// GetLists200Response struct for GetLists200Response
type GetLists200Response struct {
	Data *GetLists200ResponseData `json:"data,omitempty"`
}

// NewGetLists200Response instantiates a new GetLists200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetLists200Response() *GetLists200Response {
	this := GetLists200Response{}
	return &this
}

// NewGetLists200ResponseWithDefaults instantiates a new GetLists200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetLists200ResponseWithDefaults() *GetLists200Response {
	this := GetLists200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetLists200Response) GetData() GetLists200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetLists200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetLists200Response) GetDataOk() (*GetLists200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetLists200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetLists200ResponseData and assigns it to the Data field.
func (o *GetLists200Response) SetData(v GetLists200ResponseData) {
	o.Data = &v
}

func (o GetLists200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetLists200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetLists200Response struct {
	value *GetLists200Response
	isSet bool
}

func (v NullableGetLists200Response) Get() *GetLists200Response {
	return v.value
}

func (v *NullableGetLists200Response) Set(val *GetLists200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetLists200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetLists200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetLists200Response(val *GetLists200Response) *NullableGetLists200Response {
	return &NullableGetLists200Response{value: val, isSet: true}
}

func (v NullableGetLists200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetLists200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


