/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBounces200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBounces200Response{}

// GetBounces200Response struct for GetBounces200Response
type GetBounces200Response struct {
	Data *GetBounces200ResponseData `json:"data,omitempty"`
}

// NewGetBounces200Response instantiates a new GetBounces200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBounces200Response() *GetBounces200Response {
	this := GetBounces200Response{}
	return &this
}

// NewGetBounces200ResponseWithDefaults instantiates a new GetBounces200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBounces200ResponseWithDefaults() *GetBounces200Response {
	this := GetBounces200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetBounces200Response) GetData() GetBounces200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetBounces200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200Response) GetDataOk() (*GetBounces200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetBounces200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetBounces200ResponseData and assigns it to the Data field.
func (o *GetBounces200Response) SetData(v GetBounces200ResponseData) {
	o.Data = &v
}

func (o GetBounces200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBounces200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetBounces200Response struct {
	value *GetBounces200Response
	isSet bool
}

func (v NullableGetBounces200Response) Get() *GetBounces200Response {
	return v.value
}

func (v *NullableGetBounces200Response) Set(val *GetBounces200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBounces200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBounces200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBounces200Response(val *GetBounces200Response) *NullableGetBounces200Response {
	return &NullableGetBounces200Response{value: val, isSet: true}
}

func (v NullableGetBounces200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBounces200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


