/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetBounces200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetBounces200ResponseData{}

// GetBounces200ResponseData struct for GetBounces200ResponseData
type GetBounces200ResponseData struct {
	Results []Bounce `json:"results,omitempty"`
	Query *string `json:"query,omitempty"`
	Total *int32 `json:"total,omitempty"`
	PerPage *int32 `json:"per_page,omitempty"`
	Page *int32 `json:"page,omitempty"`
}

// NewGetBounces200ResponseData instantiates a new GetBounces200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetBounces200ResponseData() *GetBounces200ResponseData {
	this := GetBounces200ResponseData{}
	return &this
}

// NewGetBounces200ResponseDataWithDefaults instantiates a new GetBounces200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetBounces200ResponseDataWithDefaults() *GetBounces200ResponseData {
	this := GetBounces200ResponseData{}
	return &this
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetBounces200ResponseData) GetResults() []Bounce {
	if o == nil || IsNil(o.Results) {
		var ret []Bounce
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200ResponseData) GetResultsOk() ([]Bounce, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetBounces200ResponseData) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Bounce and assigns it to the Results field.
func (o *GetBounces200ResponseData) SetResults(v []Bounce) {
	o.Results = v
}

// GetQuery returns the Query field value if set, zero value otherwise.
func (o *GetBounces200ResponseData) GetQuery() string {
	if o == nil || IsNil(o.Query) {
		var ret string
		return ret
	}
	return *o.Query
}

// GetQueryOk returns a tuple with the Query field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200ResponseData) GetQueryOk() (*string, bool) {
	if o == nil || IsNil(o.Query) {
		return nil, false
	}
	return o.Query, true
}

// HasQuery returns a boolean if a field has been set.
func (o *GetBounces200ResponseData) HasQuery() bool {
	if o != nil && !IsNil(o.Query) {
		return true
	}

	return false
}

// SetQuery gets a reference to the given string and assigns it to the Query field.
func (o *GetBounces200ResponseData) SetQuery(v string) {
	o.Query = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *GetBounces200ResponseData) GetTotal() int32 {
	if o == nil || IsNil(o.Total) {
		var ret int32
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200ResponseData) GetTotalOk() (*int32, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *GetBounces200ResponseData) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given int32 and assigns it to the Total field.
func (o *GetBounces200ResponseData) SetTotal(v int32) {
	o.Total = &v
}

// GetPerPage returns the PerPage field value if set, zero value otherwise.
func (o *GetBounces200ResponseData) GetPerPage() int32 {
	if o == nil || IsNil(o.PerPage) {
		var ret int32
		return ret
	}
	return *o.PerPage
}

// GetPerPageOk returns a tuple with the PerPage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200ResponseData) GetPerPageOk() (*int32, bool) {
	if o == nil || IsNil(o.PerPage) {
		return nil, false
	}
	return o.PerPage, true
}

// HasPerPage returns a boolean if a field has been set.
func (o *GetBounces200ResponseData) HasPerPage() bool {
	if o != nil && !IsNil(o.PerPage) {
		return true
	}

	return false
}

// SetPerPage gets a reference to the given int32 and assigns it to the PerPage field.
func (o *GetBounces200ResponseData) SetPerPage(v int32) {
	o.PerPage = &v
}

// GetPage returns the Page field value if set, zero value otherwise.
func (o *GetBounces200ResponseData) GetPage() int32 {
	if o == nil || IsNil(o.Page) {
		var ret int32
		return ret
	}
	return *o.Page
}

// GetPageOk returns a tuple with the Page field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetBounces200ResponseData) GetPageOk() (*int32, bool) {
	if o == nil || IsNil(o.Page) {
		return nil, false
	}
	return o.Page, true
}

// HasPage returns a boolean if a field has been set.
func (o *GetBounces200ResponseData) HasPage() bool {
	if o != nil && !IsNil(o.Page) {
		return true
	}

	return false
}

// SetPage gets a reference to the given int32 and assigns it to the Page field.
func (o *GetBounces200ResponseData) SetPage(v int32) {
	o.Page = &v
}

func (o GetBounces200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetBounces200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Query) {
		toSerialize["query"] = o.Query
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	if !IsNil(o.PerPage) {
		toSerialize["per_page"] = o.PerPage
	}
	if !IsNil(o.Page) {
		toSerialize["page"] = o.Page
	}
	return toSerialize, nil
}

type NullableGetBounces200ResponseData struct {
	value *GetBounces200ResponseData
	isSet bool
}

func (v NullableGetBounces200ResponseData) Get() *GetBounces200ResponseData {
	return v.value
}

func (v *NullableGetBounces200ResponseData) Set(val *GetBounces200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetBounces200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetBounces200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetBounces200ResponseData(val *GetBounces200ResponseData) *NullableGetBounces200ResponseData {
	return &NullableGetBounces200ResponseData{value: val, isSet: true}
}

func (v NullableGetBounces200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetBounces200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


