/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UploadMedia200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UploadMedia200Response{}

// UploadMedia200Response struct for UploadMedia200Response
type UploadMedia200Response struct {
	Data *MediaFileObject `json:"data,omitempty"`
}

// NewUploadMedia200Response instantiates a new UploadMedia200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUploadMedia200Response() *UploadMedia200Response {
	this := UploadMedia200Response{}
	return &this
}

// NewUploadMedia200ResponseWithDefaults instantiates a new UploadMedia200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUploadMedia200ResponseWithDefaults() *UploadMedia200Response {
	this := UploadMedia200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *UploadMedia200Response) GetData() MediaFileObject {
	if o == nil || IsNil(o.Data) {
		var ret MediaFileObject
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UploadMedia200Response) GetDataOk() (*MediaFileObject, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *UploadMedia200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given MediaFileObject and assigns it to the Data field.
func (o *UploadMedia200Response) SetData(v MediaFileObject) {
	o.Data = &v
}

func (o UploadMedia200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UploadMedia200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableUploadMedia200Response struct {
	value *UploadMedia200Response
	isSet bool
}

func (v NullableUploadMedia200Response) Get() *UploadMedia200Response {
	return v.value
}

func (v *NullableUploadMedia200Response) Set(val *UploadMedia200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUploadMedia200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUploadMedia200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUploadMedia200Response(val *UploadMedia200Response) *NullableUploadMedia200Response {
	return &NullableUploadMedia200Response{value: val, isSet: true}
}

func (v NullableUploadMedia200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUploadMedia200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


