/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the DashboardCountDataCampaignsByStatus type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DashboardCountDataCampaignsByStatus{}

// DashboardCountDataCampaignsByStatus struct for DashboardCountDataCampaignsByStatus
type DashboardCountDataCampaignsByStatus struct {
	Draft *int32 `json:"draft,omitempty"`
}

// NewDashboardCountDataCampaignsByStatus instantiates a new DashboardCountDataCampaignsByStatus object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDashboardCountDataCampaignsByStatus() *DashboardCountDataCampaignsByStatus {
	this := DashboardCountDataCampaignsByStatus{}
	return &this
}

// NewDashboardCountDataCampaignsByStatusWithDefaults instantiates a new DashboardCountDataCampaignsByStatus object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDashboardCountDataCampaignsByStatusWithDefaults() *DashboardCountDataCampaignsByStatus {
	this := DashboardCountDataCampaignsByStatus{}
	return &this
}

// GetDraft returns the Draft field value if set, zero value otherwise.
func (o *DashboardCountDataCampaignsByStatus) GetDraft() int32 {
	if o == nil || IsNil(o.Draft) {
		var ret int32
		return ret
	}
	return *o.Draft
}

// GetDraftOk returns a tuple with the Draft field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DashboardCountDataCampaignsByStatus) GetDraftOk() (*int32, bool) {
	if o == nil || IsNil(o.Draft) {
		return nil, false
	}
	return o.Draft, true
}

// HasDraft returns a boolean if a field has been set.
func (o *DashboardCountDataCampaignsByStatus) HasDraft() bool {
	if o != nil && !IsNil(o.Draft) {
		return true
	}

	return false
}

// SetDraft gets a reference to the given int32 and assigns it to the Draft field.
func (o *DashboardCountDataCampaignsByStatus) SetDraft(v int32) {
	o.Draft = &v
}

func (o DashboardCountDataCampaignsByStatus) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DashboardCountDataCampaignsByStatus) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Draft) {
		toSerialize["draft"] = o.Draft
	}
	return toSerialize, nil
}

type NullableDashboardCountDataCampaignsByStatus struct {
	value *DashboardCountDataCampaignsByStatus
	isSet bool
}

func (v NullableDashboardCountDataCampaignsByStatus) Get() *DashboardCountDataCampaignsByStatus {
	return v.value
}

func (v *NullableDashboardCountDataCampaignsByStatus) Set(val *DashboardCountDataCampaignsByStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableDashboardCountDataCampaignsByStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableDashboardCountDataCampaignsByStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDashboardCountDataCampaignsByStatus(val *DashboardCountDataCampaignsByStatus) *NullableDashboardCountDataCampaignsByStatus {
	return &NullableDashboardCountDataCampaignsByStatus{value: val, isSet: true}
}

func (v NullableDashboardCountDataCampaignsByStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDashboardCountDataCampaignsByStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


