/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CampaignContentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignContentRequest{}

// CampaignContentRequest struct for CampaignContentRequest
type CampaignContentRequest struct {
	Id *int32 `json:"id,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	CampaignID *int32 `json:"CampaignID,omitempty"`
	Views *int32 `json:"views,omitempty"`
	Clicks *int32 `json:"clicks,omitempty"`
	Lists []BounceResultsInnerCampaign `json:"lists,omitempty"`
	StartedAt *string `json:"started_at,omitempty"`
	ToSend *int32 `json:"to_send,omitempty"`
	Sent *int32 `json:"sent,omitempty"`
	Uuid *string `json:"uuid,omitempty"`
	Type *string `json:"type,omitempty"`
	Name *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
	FromEmail *string `json:"from_email,omitempty"`
	Body *string `json:"body,omitempty"`
	SendAt *string `json:"send_at,omitempty"`
	Status *string `json:"status,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	Tags []string `json:"tags,omitempty"`
	TemplateId *int32 `json:"template_id,omitempty"`
	Messenger *string `json:"messenger,omitempty"`
	From *string `json:"from,omitempty"`
	To *string `json:"to,omitempty"`
}

// NewCampaignContentRequest instantiates a new CampaignContentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignContentRequest() *CampaignContentRequest {
	this := CampaignContentRequest{}
	return &this
}

// NewCampaignContentRequestWithDefaults instantiates a new CampaignContentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignContentRequestWithDefaults() *CampaignContentRequest {
	this := CampaignContentRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *CampaignContentRequest) SetId(v int32) {
	o.Id = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *CampaignContentRequest) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *CampaignContentRequest) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetCampaignID returns the CampaignID field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetCampaignID() int32 {
	if o == nil || IsNil(o.CampaignID) {
		var ret int32
		return ret
	}
	return *o.CampaignID
}

// GetCampaignIDOk returns a tuple with the CampaignID field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetCampaignIDOk() (*int32, bool) {
	if o == nil || IsNil(o.CampaignID) {
		return nil, false
	}
	return o.CampaignID, true
}

// HasCampaignID returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasCampaignID() bool {
	if o != nil && !IsNil(o.CampaignID) {
		return true
	}

	return false
}

// SetCampaignID gets a reference to the given int32 and assigns it to the CampaignID field.
func (o *CampaignContentRequest) SetCampaignID(v int32) {
	o.CampaignID = &v
}

// GetViews returns the Views field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetViews() int32 {
	if o == nil || IsNil(o.Views) {
		var ret int32
		return ret
	}
	return *o.Views
}

// GetViewsOk returns a tuple with the Views field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetViewsOk() (*int32, bool) {
	if o == nil || IsNil(o.Views) {
		return nil, false
	}
	return o.Views, true
}

// HasViews returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasViews() bool {
	if o != nil && !IsNil(o.Views) {
		return true
	}

	return false
}

// SetViews gets a reference to the given int32 and assigns it to the Views field.
func (o *CampaignContentRequest) SetViews(v int32) {
	o.Views = &v
}

// GetClicks returns the Clicks field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetClicks() int32 {
	if o == nil || IsNil(o.Clicks) {
		var ret int32
		return ret
	}
	return *o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetClicksOk() (*int32, bool) {
	if o == nil || IsNil(o.Clicks) {
		return nil, false
	}
	return o.Clicks, true
}

// HasClicks returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasClicks() bool {
	if o != nil && !IsNil(o.Clicks) {
		return true
	}

	return false
}

// SetClicks gets a reference to the given int32 and assigns it to the Clicks field.
func (o *CampaignContentRequest) SetClicks(v int32) {
	o.Clicks = &v
}

// GetLists returns the Lists field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetLists() []BounceResultsInnerCampaign {
	if o == nil || IsNil(o.Lists) {
		var ret []BounceResultsInnerCampaign
		return ret
	}
	return o.Lists
}

// GetListsOk returns a tuple with the Lists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetListsOk() ([]BounceResultsInnerCampaign, bool) {
	if o == nil || IsNil(o.Lists) {
		return nil, false
	}
	return o.Lists, true
}

// HasLists returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasLists() bool {
	if o != nil && !IsNil(o.Lists) {
		return true
	}

	return false
}

// SetLists gets a reference to the given []BounceResultsInnerCampaign and assigns it to the Lists field.
func (o *CampaignContentRequest) SetLists(v []BounceResultsInnerCampaign) {
	o.Lists = v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt) {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetStartedAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *CampaignContentRequest) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetToSend returns the ToSend field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetToSend() int32 {
	if o == nil || IsNil(o.ToSend) {
		var ret int32
		return ret
	}
	return *o.ToSend
}

// GetToSendOk returns a tuple with the ToSend field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetToSendOk() (*int32, bool) {
	if o == nil || IsNil(o.ToSend) {
		return nil, false
	}
	return o.ToSend, true
}

// HasToSend returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasToSend() bool {
	if o != nil && !IsNil(o.ToSend) {
		return true
	}

	return false
}

// SetToSend gets a reference to the given int32 and assigns it to the ToSend field.
func (o *CampaignContentRequest) SetToSend(v int32) {
	o.ToSend = &v
}

// GetSent returns the Sent field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetSent() int32 {
	if o == nil || IsNil(o.Sent) {
		var ret int32
		return ret
	}
	return *o.Sent
}

// GetSentOk returns a tuple with the Sent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetSentOk() (*int32, bool) {
	if o == nil || IsNil(o.Sent) {
		return nil, false
	}
	return o.Sent, true
}

// HasSent returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasSent() bool {
	if o != nil && !IsNil(o.Sent) {
		return true
	}

	return false
}

// SetSent gets a reference to the given int32 and assigns it to the Sent field.
func (o *CampaignContentRequest) SetSent(v int32) {
	o.Sent = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetUuid() string {
	if o == nil || IsNil(o.Uuid) {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetUuidOk() (*string, bool) {
	if o == nil || IsNil(o.Uuid) {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasUuid() bool {
	if o != nil && !IsNil(o.Uuid) {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *CampaignContentRequest) SetUuid(v string) {
	o.Uuid = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CampaignContentRequest) SetType(v string) {
	o.Type = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignContentRequest) SetName(v string) {
	o.Name = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *CampaignContentRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *CampaignContentRequest) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *CampaignContentRequest) SetBody(v string) {
	o.Body = &v
}

// GetSendAt returns the SendAt field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetSendAt() string {
	if o == nil || IsNil(o.SendAt) {
		var ret string
		return ret
	}
	return *o.SendAt
}

// GetSendAtOk returns a tuple with the SendAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetSendAtOk() (*string, bool) {
	if o == nil || IsNil(o.SendAt) {
		return nil, false
	}
	return o.SendAt, true
}

// HasSendAt returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasSendAt() bool {
	if o != nil && !IsNil(o.SendAt) {
		return true
	}

	return false
}

// SetSendAt gets a reference to the given string and assigns it to the SendAt field.
func (o *CampaignContentRequest) SetSendAt(v string) {
	o.SendAt = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CampaignContentRequest) SetStatus(v string) {
	o.Status = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *CampaignContentRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CampaignContentRequest) SetTags(v []string) {
	o.Tags = v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetTemplateId() int32 {
	if o == nil || IsNil(o.TemplateId) {
		var ret int32
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetTemplateIdOk() (*int32, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given int32 and assigns it to the TemplateId field.
func (o *CampaignContentRequest) SetTemplateId(v int32) {
	o.TemplateId = &v
}

// GetMessenger returns the Messenger field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetMessenger() string {
	if o == nil || IsNil(o.Messenger) {
		var ret string
		return ret
	}
	return *o.Messenger
}

// GetMessengerOk returns a tuple with the Messenger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetMessengerOk() (*string, bool) {
	if o == nil || IsNil(o.Messenger) {
		return nil, false
	}
	return o.Messenger, true
}

// HasMessenger returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasMessenger() bool {
	if o != nil && !IsNil(o.Messenger) {
		return true
	}

	return false
}

// SetMessenger gets a reference to the given string and assigns it to the Messenger field.
func (o *CampaignContentRequest) SetMessenger(v string) {
	o.Messenger = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *CampaignContentRequest) SetFrom(v string) {
	o.From = &v
}

// GetTo returns the To field value if set, zero value otherwise.
func (o *CampaignContentRequest) GetTo() string {
	if o == nil || IsNil(o.To) {
		var ret string
		return ret
	}
	return *o.To
}

// GetToOk returns a tuple with the To field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignContentRequest) GetToOk() (*string, bool) {
	if o == nil || IsNil(o.To) {
		return nil, false
	}
	return o.To, true
}

// HasTo returns a boolean if a field has been set.
func (o *CampaignContentRequest) HasTo() bool {
	if o != nil && !IsNil(o.To) {
		return true
	}

	return false
}

// SetTo gets a reference to the given string and assigns it to the To field.
func (o *CampaignContentRequest) SetTo(v string) {
	o.To = &v
}

func (o CampaignContentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignContentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.CampaignID) {
		toSerialize["CampaignID"] = o.CampaignID
	}
	if !IsNil(o.Views) {
		toSerialize["views"] = o.Views
	}
	if !IsNil(o.Clicks) {
		toSerialize["clicks"] = o.Clicks
	}
	if !IsNil(o.Lists) {
		toSerialize["lists"] = o.Lists
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.ToSend) {
		toSerialize["to_send"] = o.ToSend
	}
	if !IsNil(o.Sent) {
		toSerialize["sent"] = o.Sent
	}
	if !IsNil(o.Uuid) {
		toSerialize["uuid"] = o.Uuid
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.FromEmail) {
		toSerialize["from_email"] = o.FromEmail
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.SendAt) {
		toSerialize["send_at"] = o.SendAt
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.Messenger) {
		toSerialize["messenger"] = o.Messenger
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.To) {
		toSerialize["to"] = o.To
	}
	return toSerialize, nil
}

type NullableCampaignContentRequest struct {
	value *CampaignContentRequest
	isSet bool
}

func (v NullableCampaignContentRequest) Get() *CampaignContentRequest {
	return v.value
}

func (v *NullableCampaignContentRequest) Set(val *CampaignContentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignContentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignContentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignContentRequest(val *CampaignContentRequest) *NullableCampaignContentRequest {
	return &NullableCampaignContentRequest{value: val, isSet: true}
}

func (v NullableCampaignContentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignContentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


