/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetTemplateById200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetTemplateById200Response{}

// GetTemplateById200Response struct for GetTemplateById200Response
type GetTemplateById200Response struct {
	Data *Template `json:"data,omitempty"`
}

// NewGetTemplateById200Response instantiates a new GetTemplateById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetTemplateById200Response() *GetTemplateById200Response {
	this := GetTemplateById200Response{}
	return &this
}

// NewGetTemplateById200ResponseWithDefaults instantiates a new GetTemplateById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetTemplateById200ResponseWithDefaults() *GetTemplateById200Response {
	this := GetTemplateById200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetTemplateById200Response) GetData() Template {
	if o == nil || IsNil(o.Data) {
		var ret Template
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetTemplateById200Response) GetDataOk() (*Template, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetTemplateById200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given Template and assigns it to the Data field.
func (o *GetTemplateById200Response) SetData(v Template) {
	o.Data = &v
}

func (o GetTemplateById200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetTemplateById200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetTemplateById200Response struct {
	value *GetTemplateById200Response
	isSet bool
}

func (v NullableGetTemplateById200Response) Get() *GetTemplateById200Response {
	return v.value
}

func (v *NullableGetTemplateById200Response) Set(val *GetTemplateById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetTemplateById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetTemplateById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetTemplateById200Response(val *GetTemplateById200Response) *NullableGetTemplateById200Response {
	return &NullableGetTemplateById200Response{value: val, isSet: true}
}

func (v NullableGetTemplateById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetTemplateById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


