/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateCampaign200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateCampaign200Response{}

// CreateCampaign200Response struct for CreateCampaign200Response
type CreateCampaign200Response struct {
	Data *CampaignUpdate `json:"data,omitempty"`
}

// NewCreateCampaign200Response instantiates a new CreateCampaign200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateCampaign200Response() *CreateCampaign200Response {
	this := CreateCampaign200Response{}
	return &this
}

// NewCreateCampaign200ResponseWithDefaults instantiates a new CreateCampaign200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateCampaign200ResponseWithDefaults() *CreateCampaign200Response {
	this := CreateCampaign200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *CreateCampaign200Response) GetData() CampaignUpdate {
	if o == nil || IsNil(o.Data) {
		var ret CampaignUpdate
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateCampaign200Response) GetDataOk() (*CampaignUpdate, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *CreateCampaign200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given CampaignUpdate and assigns it to the Data field.
func (o *CreateCampaign200Response) SetData(v CampaignUpdate) {
	o.Data = &v
}

func (o CreateCampaign200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateCampaign200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableCreateCampaign200Response struct {
	value *CreateCampaign200Response
	isSet bool
}

func (v NullableCreateCampaign200Response) Get() *CreateCampaign200Response {
	return v.value
}

func (v *NullableCreateCampaign200Response) Set(val *CreateCampaign200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateCampaign200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateCampaign200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateCampaign200Response(val *CreateCampaign200Response) *NullableCreateCampaign200Response {
	return &NullableCreateCampaign200Response{value: val, isSet: true}
}

func (v NullableCreateCampaign200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateCampaign200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


