/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetSubscriberBouncesById200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSubscriberBouncesById200Response{}

// GetSubscriberBouncesById200Response struct for GetSubscriberBouncesById200Response
type GetSubscriberBouncesById200Response struct {
	Data []Bounce `json:"data,omitempty"`
}

// NewGetSubscriberBouncesById200Response instantiates a new GetSubscriberBouncesById200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSubscriberBouncesById200Response() *GetSubscriberBouncesById200Response {
	this := GetSubscriberBouncesById200Response{}
	return &this
}

// NewGetSubscriberBouncesById200ResponseWithDefaults instantiates a new GetSubscriberBouncesById200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSubscriberBouncesById200ResponseWithDefaults() *GetSubscriberBouncesById200Response {
	this := GetSubscriberBouncesById200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetSubscriberBouncesById200Response) GetData() []Bounce {
	if o == nil || IsNil(o.Data) {
		var ret []Bounce
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSubscriberBouncesById200Response) GetDataOk() ([]Bounce, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetSubscriberBouncesById200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []Bounce and assigns it to the Data field.
func (o *GetSubscriberBouncesById200Response) SetData(v []Bounce) {
	o.Data = v
}

func (o GetSubscriberBouncesById200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSubscriberBouncesById200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetSubscriberBouncesById200Response struct {
	value *GetSubscriberBouncesById200Response
	isSet bool
}

func (v NullableGetSubscriberBouncesById200Response) Get() *GetSubscriberBouncesById200Response {
	return v.value
}

func (v *NullableGetSubscriberBouncesById200Response) Set(val *GetSubscriberBouncesById200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSubscriberBouncesById200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSubscriberBouncesById200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSubscriberBouncesById200Response(val *GetSubscriberBouncesById200Response) *NullableGetSubscriberBouncesById200Response {
	return &NullableGetSubscriberBouncesById200Response{value: val, isSet: true}
}

func (v NullableGetSubscriberBouncesById200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSubscriberBouncesById200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


