/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LanguagePack type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LanguagePack{}

// LanguagePack struct for LanguagePack
type LanguagePack struct {
	Data *LanguagePackData `json:"data,omitempty"`
}

// NewLanguagePack instantiates a new LanguagePack object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLanguagePack() *LanguagePack {
	this := LanguagePack{}
	return &this
}

// NewLanguagePackWithDefaults instantiates a new LanguagePack object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLanguagePackWithDefaults() *LanguagePack {
	this := LanguagePack{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *LanguagePack) GetData() LanguagePackData {
	if o == nil || IsNil(o.Data) {
		var ret LanguagePackData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LanguagePack) GetDataOk() (*LanguagePackData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *LanguagePack) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given LanguagePackData and assigns it to the Data field.
func (o *LanguagePack) SetData(v LanguagePackData) {
	o.Data = &v
}

func (o LanguagePack) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LanguagePack) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableLanguagePack struct {
	value *LanguagePack
	isSet bool
}

func (v NullableLanguagePack) Get() *LanguagePack {
	return v.value
}

func (v *NullableLanguagePack) Set(val *LanguagePack) {
	v.value = val
	v.isSet = true
}

func (v NullableLanguagePack) IsSet() bool {
	return v.isSet
}

func (v *NullableLanguagePack) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLanguagePack(val *LanguagePack) *NullableLanguagePack {
	return &NullableLanguagePack{value: val, isSet: true}
}

func (v NullableLanguagePack) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLanguagePack) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


