/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetCampaigns200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetCampaigns200Response{}

// GetCampaigns200Response struct for GetCampaigns200Response
type GetCampaigns200Response struct {
	Data *GetCampaigns200ResponseData `json:"data,omitempty"`
}

// NewGetCampaigns200Response instantiates a new GetCampaigns200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetCampaigns200Response() *GetCampaigns200Response {
	this := GetCampaigns200Response{}
	return &this
}

// NewGetCampaigns200ResponseWithDefaults instantiates a new GetCampaigns200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetCampaigns200ResponseWithDefaults() *GetCampaigns200Response {
	this := GetCampaigns200Response{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetCampaigns200Response) GetData() GetCampaigns200ResponseData {
	if o == nil || IsNil(o.Data) {
		var ret GetCampaigns200ResponseData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetCampaigns200Response) GetDataOk() (*GetCampaigns200ResponseData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetCampaigns200Response) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given GetCampaigns200ResponseData and assigns it to the Data field.
func (o *GetCampaigns200Response) SetData(v GetCampaigns200ResponseData) {
	o.Data = &v
}

func (o GetCampaigns200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetCampaigns200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableGetCampaigns200Response struct {
	value *GetCampaigns200Response
	isSet bool
}

func (v NullableGetCampaigns200Response) Get() *GetCampaigns200Response {
	return v.value
}

func (v *NullableGetCampaigns200Response) Set(val *GetCampaigns200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetCampaigns200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetCampaigns200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetCampaigns200Response(val *GetCampaigns200Response) *NullableGetCampaigns200Response {
	return &NullableGetCampaigns200Response{value: val, isSet: true}
}

func (v NullableGetCampaigns200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetCampaigns200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


