/*
Listmonk

The API collection for listmonk

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CampaignRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CampaignRequest{}

// CampaignRequest struct for CampaignRequest
type CampaignRequest struct {
	Name *string `json:"name,omitempty"`
	Subject *string `json:"subject,omitempty"`
	Lists []float32 `json:"lists,omitempty"`
	FromEmail *string `json:"from_email,omitempty"`
	ContentType *string `json:"content_type,omitempty"`
	Messenger *string `json:"messenger,omitempty"`
	Type *string `json:"type,omitempty"`
	Tags []string `json:"tags,omitempty"`
	SendLater *bool `json:"send_later,omitempty"`
	SendAt *CampaignRequestSendAt `json:"send_at,omitempty"`
}

// NewCampaignRequest instantiates a new CampaignRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignRequest() *CampaignRequest {
	this := CampaignRequest{}
	return &this
}

// NewCampaignRequestWithDefaults instantiates a new CampaignRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignRequestWithDefaults() *CampaignRequest {
	this := CampaignRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *CampaignRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *CampaignRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *CampaignRequest) SetName(v string) {
	o.Name = &v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *CampaignRequest) GetSubject() string {
	if o == nil || IsNil(o.Subject) {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetSubjectOk() (*string, bool) {
	if o == nil || IsNil(o.Subject) {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *CampaignRequest) HasSubject() bool {
	if o != nil && !IsNil(o.Subject) {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *CampaignRequest) SetSubject(v string) {
	o.Subject = &v
}

// GetLists returns the Lists field value if set, zero value otherwise.
func (o *CampaignRequest) GetLists() []float32 {
	if o == nil || IsNil(o.Lists) {
		var ret []float32
		return ret
	}
	return o.Lists
}

// GetListsOk returns a tuple with the Lists field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetListsOk() ([]float32, bool) {
	if o == nil || IsNil(o.Lists) {
		return nil, false
	}
	return o.Lists, true
}

// HasLists returns a boolean if a field has been set.
func (o *CampaignRequest) HasLists() bool {
	if o != nil && !IsNil(o.Lists) {
		return true
	}

	return false
}

// SetLists gets a reference to the given []float32 and assigns it to the Lists field.
func (o *CampaignRequest) SetLists(v []float32) {
	o.Lists = v
}

// GetFromEmail returns the FromEmail field value if set, zero value otherwise.
func (o *CampaignRequest) GetFromEmail() string {
	if o == nil || IsNil(o.FromEmail) {
		var ret string
		return ret
	}
	return *o.FromEmail
}

// GetFromEmailOk returns a tuple with the FromEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetFromEmailOk() (*string, bool) {
	if o == nil || IsNil(o.FromEmail) {
		return nil, false
	}
	return o.FromEmail, true
}

// HasFromEmail returns a boolean if a field has been set.
func (o *CampaignRequest) HasFromEmail() bool {
	if o != nil && !IsNil(o.FromEmail) {
		return true
	}

	return false
}

// SetFromEmail gets a reference to the given string and assigns it to the FromEmail field.
func (o *CampaignRequest) SetFromEmail(v string) {
	o.FromEmail = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *CampaignRequest) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *CampaignRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *CampaignRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetMessenger returns the Messenger field value if set, zero value otherwise.
func (o *CampaignRequest) GetMessenger() string {
	if o == nil || IsNil(o.Messenger) {
		var ret string
		return ret
	}
	return *o.Messenger
}

// GetMessengerOk returns a tuple with the Messenger field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetMessengerOk() (*string, bool) {
	if o == nil || IsNil(o.Messenger) {
		return nil, false
	}
	return o.Messenger, true
}

// HasMessenger returns a boolean if a field has been set.
func (o *CampaignRequest) HasMessenger() bool {
	if o != nil && !IsNil(o.Messenger) {
		return true
	}

	return false
}

// SetMessenger gets a reference to the given string and assigns it to the Messenger field.
func (o *CampaignRequest) SetMessenger(v string) {
	o.Messenger = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CampaignRequest) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CampaignRequest) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CampaignRequest) SetType(v string) {
	o.Type = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *CampaignRequest) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *CampaignRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *CampaignRequest) SetTags(v []string) {
	o.Tags = v
}

// GetSendLater returns the SendLater field value if set, zero value otherwise.
func (o *CampaignRequest) GetSendLater() bool {
	if o == nil || IsNil(o.SendLater) {
		var ret bool
		return ret
	}
	return *o.SendLater
}

// GetSendLaterOk returns a tuple with the SendLater field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetSendLaterOk() (*bool, bool) {
	if o == nil || IsNil(o.SendLater) {
		return nil, false
	}
	return o.SendLater, true
}

// HasSendLater returns a boolean if a field has been set.
func (o *CampaignRequest) HasSendLater() bool {
	if o != nil && !IsNil(o.SendLater) {
		return true
	}

	return false
}

// SetSendLater gets a reference to the given bool and assigns it to the SendLater field.
func (o *CampaignRequest) SetSendLater(v bool) {
	o.SendLater = &v
}

// GetSendAt returns the SendAt field value if set, zero value otherwise.
func (o *CampaignRequest) GetSendAt() CampaignRequestSendAt {
	if o == nil || IsNil(o.SendAt) {
		var ret CampaignRequestSendAt
		return ret
	}
	return *o.SendAt
}

// GetSendAtOk returns a tuple with the SendAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignRequest) GetSendAtOk() (*CampaignRequestSendAt, bool) {
	if o == nil || IsNil(o.SendAt) {
		return nil, false
	}
	return o.SendAt, true
}

// HasSendAt returns a boolean if a field has been set.
func (o *CampaignRequest) HasSendAt() bool {
	if o != nil && !IsNil(o.SendAt) {
		return true
	}

	return false
}

// SetSendAt gets a reference to the given CampaignRequestSendAt and assigns it to the SendAt field.
func (o *CampaignRequest) SetSendAt(v CampaignRequestSendAt) {
	o.SendAt = &v
}

func (o CampaignRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CampaignRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Subject) {
		toSerialize["subject"] = o.Subject
	}
	if !IsNil(o.Lists) {
		toSerialize["lists"] = o.Lists
	}
	if !IsNil(o.FromEmail) {
		toSerialize["from_email"] = o.FromEmail
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.Messenger) {
		toSerialize["messenger"] = o.Messenger
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.SendLater) {
		toSerialize["send_later"] = o.SendLater
	}
	if !IsNil(o.SendAt) {
		toSerialize["send_at"] = o.SendAt
	}
	return toSerialize, nil
}

type NullableCampaignRequest struct {
	value *CampaignRequest
	isSet bool
}

func (v NullableCampaignRequest) Get() *CampaignRequest {
	return v.value
}

func (v *NullableCampaignRequest) Set(val *CampaignRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignRequest(val *CampaignRequest) *NullableCampaignRequest {
	return &NullableCampaignRequest{value: val, isSet: true}
}

func (v NullableCampaignRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


